mutation addSpot($spot: SpotInput!) {
  addSpot(spot: $spot) {
    _id
    name
    lat
    lng
    img {
      data
      contentType
    }
    containers {
      _id
      contType
      count
      probability
    }
  }
}
